Deploy docs from CI
marda-alliance/metadata_extractors_api pull request #25
Opened 2024-01-17 23:04 UTC by ml-evs

Stealing some workflows from the schema registry, this PR attempts to deploy docs on merges to main.

2024-01-18 12:44 UTC, PeterKraus requested changes

2024-01-18 13:04 UTC, ml-evs commented
Just deploying on all commits for now, for some reason the docs are served at https://marda-alliance.github.io/metadata_extractors_api/main/ (i.e. /main) rather than the base.

2024-01-22 12:36 UTC, PeterKraus commented
Yeah, that's as expected. I prefer to make a manual build of every version after release and keep them in their own folder. I'll push a patch to this branch to implement that.

2024-01-22 12:45 UTC, PeterKraus approved these changes

2024-01-22 12:45 UTC, merged